import Head from "next/head";
import { Inter } from "@next/font/google";
import Nav from "@/component/Nav";
import Header from "@/component/Home";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="bg-gradient-to-r from-white via-emerald-50 to-blue-100">
				<Nav />
				<Header />
			</div>
		</>
	);
}
