import Head from "next/head";
import { Inter } from "@next/font/google";
import Nav from "@/component/Nav";
import Header from "@/component/Home";
import Main from "@/component/Main";
import Footer from "@/component/Footer";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });
export async function getStaticProps() {
	const res = await fetch("http://localhost:8000/foods");
	const foods = await res.json();

	return {
		props: {
			foods,
		},
	};
}

export default function Home({ foods }) {
	const [value, getValue] = useState([]);
	const handleCatagory = (e) => {
		getValue(e.target.value);
	};
	return (
		<>
			<div className="bg-gradient-to-r from-white via-emerald-50 to-blue-100">
				<Head>
					<title>fooder | homepage</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
				</Head>

				<Header />
				<Main foods={foods} handleCatagory={handleCatagory} />
			</div>
		</>
	);
}
