const data = {
	foods: [
		{
			id: "1",
			title: "Teekha Murg",
			desc: "For all the spice fans! Tender chicken spiked with fiery masalas, cooked in mustard oil with the tang of tomatoes to balance the flavours. This spicy delicacy should be teamed with either rumali roti or khamiri roti to balance the spiciness. If you are a die-hard chicken lover, this Indian chicken recipe is for you.",
			price: 120,
			catagory: "chicken",
			image: "/img/c1.png",
		},
		{
			id: "2",
			title: "Murg Malaiwala",
			desc: "Chicken drumsticks laced with delicate flavors of cream, milk, saffron, rose petals and mild spices. This recipe is not made with oil or ghee; but it will definitely make a great start to your festive cheer. Make sure you garnish the dish with raw almonds that only enhance the dish's flavour. ",
			price: 200,
			catagory: "chicken",
			image: "/img/c2.png",
		},
		{
			id: "3",
			title: "Chicken Chettinad",
			desc: "For the ones who love a fiery palette! Chettinad cuisine from Tamil Nadu is known to be the spiciest cuisine in India. Chicken tossed with southern spices and coconut-y paste. Remember, this one's not for people who do not like it spicy. ",
			price: 130,
			catagory: "chicken",
			image: "/img/c3.png",
		},
		{
			id: "4",
			title: "Butter Chicken",
			desc: "Straight from a Punjabi kitchen, butter chicken has been an instant hit through the years. Marinated overnight, the chicken is roasted and cooked in tomato puree, cream and masalas. Enjoy the classic creaminess of the dish with this recipe. ",
			price: 150,
			catagory: "chicken",
			image: "/img/c6.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/cu1.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/cu2.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/cu3.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/cu4.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/cu5.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/cu6.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/d2.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/d3.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/d4.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/d1.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/d5.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/d6.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/d7.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/d8.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/f3.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/f2.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/f1.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/f4.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/f5.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/f6.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/f7.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/f8.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/f9.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/f10.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/i7.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/i6.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/i5.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/i4.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/i3.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/i2.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/i1.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/fi1.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/fi2.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/fi3.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/fi4.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/fi5.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/r1.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/r2.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/r3.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/r4.png",
		},
		{
			id: "5",
			title: "Chicken Sukka",
			desc: "A speciality from Mangalore, chicken sukka has a host of spices combined with the goodness of coconut. This one is a semi-dry dish that can perfectly compliment your dinner table.",
			price: 175,
			catagory: "chicken",
			image: "/img/r5.png",
		},
	],
};
export default data;
