const data = {
	details: [
		{
			id: "1",
			title: "Agents of Social",
			desc: "Identity Design for Innsbruck International, Biennial of the Arts",
			link: "home",
			// font: "font-sans",
			color: "bg-red-700",
			text: "text-black",
			image: "/assets/news.jpg",
		},
		{
			id: "2",
			title: "Agents of Social Change",
			desc: "Identity Design for Innsbruck International, Biennial of the Arts",
			link: "strategy",
			color: "bg-blue-900",
			text: "text-black",
			// font: "font-serif",
			image: "/assets/1.jpg",
		},
		{
			id: "3",
			title: "Agents of Social Change",
			desc: "Identity Design for Innsbruck International, Biennial of the Arts",
			link: "about",
			color: "bg-black",
			text: "text-white",
			// font: "font-sans",
			image: "/assets/2.jpg",
		},
		{
			id: "4",
			title: "Agents of Social Change",
			desc: "Identity Design for Innsbruck International, Biennial of the Arts",
			link: "#home",
			color: "bg-green-900",
			text: "text-black",
			// font: "font-sans",
			image: "/assets/3.jpg",
		},
		{
			id: "5",
			title: "Agents of Social Change",
			desc: "Identity Design for Innsbruck International, Biennial of the Arts",
			link: "#home",
			color: "bg-green-900",
			text: "text-black",
			// font: "font-sans",
			image: "/assets/4.jpg",
		},
		{
			id: "6",
			title: "Agents of Social Change",
			desc: "Identity Design for Innsbruck International, Biennial of the Arts",
			link: "#home",
			color: "bg-green-900",
			text: "text-white",
			// font: "font-sans",
			image: "/assets/5.jpg",
		},
		{
			id: "7",
			title: "Agents of Social Change",
			desc: "Identity Design for Innsbruck International, Biennial of the Arts",
			link: "#home",
			color: "bg-green-900",
			text: "text-black",
			// font: "font-sans",
			image: "/assets/6.jpg",
		},
	],
};
export default data;
